version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    container_name: brainag-container
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - '5173:5173'
